--- #YAML:1.0
name:               Devel-PtrTable
version:            0.01
abstract:           Interface to perl's old-new pointer mapping for cloning
author:
    - M. Nunberg <mnunberg@haskalah.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Task::Weaken:  0
    Test::More:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
